### ISSUE TITLE
Standardize frontend tags

### ISSUE THREAD

**Issue by xujustinj** [loolabs/waterpark#102]
Currently we have 3 competing implementations of Club and Event tags, we should collapse this into one common implementation that can serve all 3 uses (such as colours)

**Comment by wang-em** [comment]
We have three components that implement a "tag":
1. ListCardTag in client/components/events/EventListView/EventListView.tsx
2. Tag in client/components/clubs/Tag.tsx
3. Category in client/components/Category.tsx

Let's create a common Tag component in client/components/Tag.tsx that
- matches the tag style decided by Design
- automatically colours the tag based on the text
- can replace the 3 tag implementations currently floating around

For now, we probably can't replace the extra components built around the tags for layout (e.g. TagRow and TagGroup in client/components/clubs/Tag.tsx), but feel free to modify those components to work with the common Tag
